networks:
  backend:
    driver: bridge

volumes:
  ${COMPOSE_PROJECT_NAME}-mysql:
    external: true

services:
  node:
    build:
      context: ${PROJECT_PATH}
      dockerfile: .docker/frontend/Dockerfile
      target: ${NODE_STAGE}
      args:
        - NODE_VERSION=${NODE_VERSION}
    restart: 'no'
    volumes:
      - ${PROJECT_PATH}/frontend:/home/node/app
    networks:
      - backend
    ports:
      - '80:80'
  api:
    build:
      context: ${PROJECT_PATH}
      dockerfile: .docker/backend/Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    restart: 'no'
    volumes:
      - ${PROJECT_PATH}/backend/src:/usr/src/app/src
    networks:
      - backend
    ports:
      - '8000:8000'
    depends_on:
      - mysql
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: 'no'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ${COMPOSE_PROJECT_NAME}-mysql:/var/lib/mysql
    networks:
      - backend
