version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test_project_database
      MYSQL_PASSWORD: 12345

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ../  # Use the directory containing `docker-compose.yml` as the context
      dockerfile: .docker/app/Dockerfile  # Path to the Dockerfile relative to the context
    command: /app/src/manage.py runserver 0.0.0.0:8001
    volumes:
      - ../src:/app/src
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
     - DJANGO_SETTINGS_MODULE=djangoProject.settings

  nginx:
    build:
      context: ..
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media

volumes:
  db_data:
  static_volume:
  media_volume:
