name: Backend
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 87.228.19.52 >> ~/.ssh/known_hosts

    - name: Remove existing files on the server
      run: ssh root@87.228.19.52 "rm -rf /backend-project/*"

    - name: Copy files to server using rsync
      run: |
        rsync -avz --delete --exclude '.git/' . root@87.228.19.52:/

    - name: Deploy on server
      run: ssh root@87.228.19.52 "cd /backend-project/.docker && docker-compose down && docker-compose up --build -d"
